// Auto-generated list of KP skills
export const KP_SKILLS = [
    { id: 'bm-kp1', code: 'KP1', name: 'KP1 — Huruf-huruf vokal', description: '*(a, e, i, o, u)*', category: 'bm', file: './bm/kp1.js' },
    { id: 'bm-kp2', code: 'KP2', name: 'KP2 — Huruf-huruf kecil', description: 'Huruf-huruf kecil', category: 'bm', file: './bm/kp2.js' },
    { id: 'bm-kp3', code: 'KP3', name: 'KP3 — Huruf-huruf besar', description: 'Huruf-huruf besar', category: 'bm', file: './bm/kp3.js' },
    { id: 'bm-kp4', code: 'KP4', name: 'KP4 — Suku kata KV', description: 'Suku kata KV', category: 'bm', file: './bm/kp4.js' },
    { id: 'bm-kp9', code: 'KP9', name: 'KP9 — Suku kata KVK', description: 'Suku kata KVK', category: 'bm', file: './bm/kp9.js' },
    { id: 'bm-kp17', code: 'KP17', name: 'KP17 — Suku kata KVKK', description: 'Suku kata KVKK', category: 'bm', file: './bm/kp17.js' },
    { id: 'bm-kp5', code: 'KP5', name: 'KP5 — Perkataan KV + KV', description: 'Perkataan KV + KV', category: 'bm', file: './bm/kp5.js' },
    { id: 'bm-kp6', code: 'KP6', name: 'KP6 — Perkataan V + KV', description: 'Perkataan V + KV', category: 'bm', file: './bm/kp6.js' },
    { id: 'bm-kp7', code: 'KP7', name: 'KP7 — Perkataan KV + KV + KV', description: 'Perkataan KV + KV + KV', category: 'bm', file: './bm/kp7.js' },
    { id: 'bm-kp8', code: 'KP8', name: 'KP8 — Perkataan KVK', description: 'Perkataan KVK', category: 'bm', file: './bm/kp8.js' },
    { id: 'bm-kp10', code: 'KP10', name: 'KP10 — Perkataan V + KVK', description: 'Perkataan V + KVK', category: 'bm', file: './bm/kp10.js' },
    { id: 'bm-kp11', code: 'KP11', name: 'KP11 — Perkataan KV + KVK', description: 'Perkataan KV + KVK', category: 'bm', file: './bm/kp11.js' },
    { id: 'bm-kp12', code: 'KP12', name: 'KP12 — Perkataan KVK + KV', description: 'Perkataan KVK + KV', category: 'bm', file: './bm/kp12.js' },
    { id: 'bm-kp13', code: 'KP13', name: 'KP13 — Perkataan KVK + KVK', description: 'Perkataan KVK + KVK', category: 'bm', file: './bm/kp13.js' },
    { id: 'bm-kp14', code: 'KP14', name: 'KP14 — Perkataan KV + KV + KVK', description: 'Perkataan KV + KV + KVK', category: 'bm', file: './bm/kp14.js' },
    { id: 'bm-kp15', code: 'KP15', name: 'KP15 — Perkataan KVK + KV + KVK', description: 'Perkataan KVK + KV + KVK', category: 'bm', file: './bm/kp15.js' },
    { id: 'bm-kp16', code: 'KP16', name: 'KP16 — Perkataan KVKK', description: 'Perkataan KVKK', category: 'bm', file: './bm/kp16.js' },
    { id: 'bm-kp18', code: 'KP18', name: 'KP18 — Perkataan KV + KVKK', description: 'Perkataan KV + KVKK', category: 'bm', file: './bm/kp18.js' },
    { id: 'bm-kp19', code: 'KP19', name: 'KP19 — Perkataan V + KVKK', description: 'Perkataan V + KVKK', category: 'bm', file: './bm/kp19.js' },
    { id: 'bm-kp20', code: 'KP20', name: 'KP20 — Perkataan KVK + KVKK', description: 'Perkataan KVK + KVKK', category: 'bm', file: './bm/kp20.js' },
    { id: 'bm-kp21', code: 'KP21', name: 'KP21 — Perkataan KVKK + KV', description: 'Perkataan KVKK + KV', category: 'bm', file: './bm/kp21.js' },
    { id: 'bm-kp22', code: 'KP22', name: 'KP22 — Perkataan KVKK + KVK', description: 'Perkataan KVKK + KVK', category: 'bm', file: './bm/kp22.js' },
    { id: 'bm-kp23', code: 'KP23', name: 'KP23 — Perkataan KVKK + KVKK', description: 'Perkataan KVKK + KVKK', category: 'bm', file: './bm/kp23.js' },
    { id: 'bm-kp24', code: 'KP24', name: 'KP24 — Perkataan KV + KV + KVKK', description: 'Perkataan KV + KV + KVKK', category: 'bm', file: './bm/kp24.js' },
    { id: 'bm-kp25', code: 'KP25', name: 'KP25 — Perkataan KV + KVK + KVKK', description: 'Perkataan KV + KVK + KVKK', category: 'bm', file: './bm/kp25.js' },
    { id: 'bm-kp26', code: 'KP26', name: 'KP26 — Perkataan KVK + KV + KVKK', description: 'Perkataan KVK + KV + KVKK', category: 'bm', file: './bm/kp26.js' },
    { id: 'bm-kp27', code: 'KP27', name: 'KP27 — Perkataan KVKK + KV + KVK', description: 'Perkataan KVKK + KV + KVK', category: 'bm', file: './bm/kp27.js' },
    { id: 'bm-kp28', code: 'KP28', name: 'KP28 — Perkataan KV + KVKK + KVK', description: 'Perkataan KV + KVKK + KVK', category: 'bm', file: './bm/kp28.js' },
    { id: 'bm-kp29', code: 'KP29', name: 'KP29 — Perkataan yang melibatkan diftong & vokal berganding', description: '*(cth: ai, au, oi; ia, ua, ea…)*', category: 'bm', file: './bm/kp29.js' },
    { id: 'bm-kp30', code: 'KP30', name: 'KP30 — Perkataan yang melibatkan huruf konsonan bergabung (digraf)', description: '*(cth: ng, ny, kh, gh, sy)*', category: 'bm', file: './bm/kp30.js' },
    { id: 'bm-kp31', code: 'KP31', name: 'KP31 — Membaca & membina ayat mudah', description: 'Membaca & membina ayat mudah', category: 'bm', file: './bm/kp31.js' },
    { id: 'bm-kp32', code: 'KP32', name: 'KP32 — Bacaan & pemahaman', description: 'Bacaan & pemahaman', category: 'bm', file: './bm/kp32.js' },
    { id: 'math-kp1', code: 'KP1', name: 'KP1 — 前数（Pra Nombor）', description: '前数（Pra Nombor）', category: 'math', file: './math/kp1.js' },
    { id: 'math-kp2', code: 'KP2', name: 'KP2 — 数的概念（Konsep Nombor）', description: '数的概念（Konsep Nombor）', category: 'math', file: './math/kp2.js' },
    { id: 'math-kp3', code: 'KP3', name: 'KP3 — 整数（Nombor Bulat）', description: '整数（Nombor Bulat）', category: 'math', file: './math/kp3.js' },
    { id: 'math-kp3.1', code: 'KP3.1', name: 'KP3.1 — 整数至 10', description: '：读写、顺/逆序、大小比较与排序。', category: 'math', file: './math/kp3.1.js' },
    { id: 'math-kp3.2', code: 'KP3.2', name: 'KP3.2 — 整数至 20', description: '整数至 20', category: 'math', file: './math/kp3.2.js' },
    { id: 'math-kp3.3', code: 'KP3.3', name: 'KP3.3 — 整数至 100', description: '整数至 100', category: 'math', file: './math/kp3.3.js' },
    { id: 'math-kp3.4', code: 'KP3.4', name: 'KP3.4 — 整数至 1000', description: '整数至 1000', category: 'math', file: './math/kp3.4.js' },
    { id: 'math-kp4', code: 'KP4', name: 'KP4 — 加法（Operasi Tambah）', description: '加法（Operasi Tambah）', category: 'math', file: './math/kp4.js' },
    { id: 'math-kp4.1', code: 'KP4.1', name: 'KP4.1 — ≤10', description: '（不进位/进位的初步）', category: 'math', file: './math/kp4.1.js' },
    { id: 'math-kp4.2', code: 'KP4.2', name: 'KP4.2 — ≤18', description: '（含进位情形）', category: 'math', file: './math/kp4.2.js' },
    { id: 'math-kp4.3', code: 'KP4.3', name: 'KP4.3 — ≤100', description: '≤100', category: 'math', file: './math/kp4.3.js' },
    { id: 'math-kp4.4', code: 'KP4.4', name: 'KP4.4 — ≤1000', description: '≤1000', category: 'math', file: './math/kp4.4.js' },
    { id: 'math-kp5', code: 'KP5', name: 'KP5 — 减法（Operasi Tolak）', description: '减法（Operasi Tolak）', category: 'math', file: './math/kp5.js' },
    { id: 'math-kp5.1', code: 'KP5.1', name: 'KP5.1 — ≤10', description: '（不借位/借位）', category: 'math', file: './math/kp5.1.js' },
    { id: 'math-kp5.2', code: 'KP5.2', name: 'KP5.2 — ≤18', description: '≤18', category: 'math', file: './math/kp5.2.js' },
    { id: 'math-kp5.3', code: 'KP5.3', name: 'KP5.3 — ≤100', description: '≤100', category: 'math', file: './math/kp5.3.js' },
    { id: 'math-kp5.4', code: 'KP5.4', name: 'KP5.4 — ≤1000', description: '≤1000', category: 'math', file: './math/kp5.4.js' },
    { id: 'math-kp6', code: 'KP6', name: 'KP6 — 乘法（Operasi Darab）', description: '乘法（Operasi Darab）', category: 'math', file: './math/kp6.js' },
    { id: 'math-kp7', code: 'KP7', name: 'KP7 — 除法（Operasi Bahagi）', description: '除法（Operasi Bahagi）', category: 'math', file: './math/kp7.js' },
    { id: 'math-kp8', code: 'KP8', name: 'KP8 — 货币（Wang）', description: '货币（Wang）', category: 'math', file: './math/kp8.js' },
    { id: 'math-kp8.1', code: 'KP8.1', name: 'KP8.1 — 至 RM10', description: '至 RM10', category: 'math', file: './math/kp8.1.js' },
    { id: 'math-kp8.2', code: 'KP8.2', name: 'KP8.2 — 至 RM100', description: '至 RM100', category: 'math', file: './math/kp8.2.js' },
    { id: 'math-kp8.3', code: 'KP8.3', name: 'KP8.3 — 至 RM1000', description: '至 RM1000', category: 'math', file: './math/kp8.3.js' },
    { id: 'math-kp9', code: 'KP9', name: 'KP9 — 时间与时钟（Masa dan Waktu）', description: '时间与时钟（Masa dan Waktu）', category: 'math', file: './math/kp9.js' }
];

export default KP_SKILLS;
